webhook_data = {
    "id": 1499708386,
    "domain": "test",
    "status": "success",
    "reference": "5jtitec2tm",
    "amount": 5000000,
    "message": None,
    "gateway_response": "Successful",
    "paid_at": "2021-12-11T00:52:55.000Z",
    "created_at": "2021-12-11T00:52:04.000Z",
    "channel": "card",
    "currency": "NGN",
    "ip_address": "197.210.76.235",
    "metadata": {"user_id": "1"},
    "log": {
        "start_time": 1639183967,
        "time_spent": 8,
        "attempts": 1,
        "errors": 0,
        "success": True,
        "mobile": False,
        "input": [],
        "history": [
            {"type": "action", "message": "Attempted to pay with card", "time": 6},
            {"type": "success", "message": "Successfully paid with card", "time": 8},
        ],
    },
    "fees": 85000,
    "fees_split": None,
    "authorization": {
        "authorization_code": "AUTH_f9q3h9b0g8",
        "bin": "408408",
        "last4": "4081",
        "exp_month": "12",
        "exp_year": "2030",
        "channel": "card",
        "card_type": "visa ",
        "bank": "TEST BANK",
        "country_code": "NG",
        "brand": "visa",
        "reusable": True,
        "signature": "SIG_yBjn5RzLN1p17nBYDgWi",
        "account_name": None,
        "receiver_bank_account_number": None,
        "receiver_bank": None,
    },
    "customer": {
        "id": 64107141,
        "first_name": None,
        "last_name": None,
        "email": "admin@gmail.com",
        "customer_code": "CUS_lhx0fet131a070z",
        "phone": None,
        "metadata": None,
        "risk_action": "default",
        "international_format_phone": None,
    },
    "plan": None,
    "split": {},
    "order_id": None,
    "paidAt": "2021-12-11T00:52:55.000Z",
    "createdAt": "2021-12-11T00:52:04.000Z",
    "requested_amount": 5000000,
    "pos_transaction_data": None,
    "source": None,
    "fees_breakdown": None,
    "transaction_date": "2021-12-11T00:52:04.000Z",
    "plan_object": {},
    "subaccount": {},
}
