# Generated by Django 2.2 on 2021-12-09 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paystack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('charge_type', models.CharField(choices=[('GATEWAY_PURCHASE', 'Gateway Purchase'), ('TRANSFER', 'Transfer')], max_length=30)),
                ('amount', models.FloatField(max_length=19)),
                ('currency', models.CharField(max_length=5)),
                ('txRef', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date_time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='paystackcustomer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BasePaymentHistory',
        ),
    ]
